name: Check Code for errors

on: [push,workflow_dispatch]
jobs:
  build:
    name: Start coding ...
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
       - name: Setup and run build
         run: |
          git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
          git clone https://${{ secrets.tok}}@github.com/raja007hacker/youtubedev.git
          git clone https://github.com/raja007hacker/testcode
          cp testcode/mydata.bin youtubedev/mydata.bin
          cd youtubedev;pip3 install -r requirements.txt;python3 testcode.py
